services:
  postgres-db:
    image: postgres:16-alpine
    container_name: sonus-postgres-metadata-db
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - streaming-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: sonus-minio
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - streaming-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    container_name: sonus-kafka
    environment:
      - KAFKA_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9094
    ports:
      - "0.0.0.0:9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - streaming-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: sonus-kafka-ui
    ports:
      - "8080:8080"
    restart: "always"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    depends_on:
      - kafka
    networks:
      - streaming-network

  mongodb:
    image: mongo:latest
    container_name: sonus-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - streaming-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # My Microservices

  api-gateway:
    build: ./api-gateway
    container_name: sonus-api-gateway
    ports:
      - "9040:9040"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    networks:
      - streaming-network

  user-auth-service:
    build: ./user-auth-service
    container_name: sonus-user-auth-service
    environment:
      - SPRING_R2DBC_URL=${DB_URL}
      - SPRING_R2DBC_USERNAME=${DB_USERNAME}
      - SPRING_R2DBC_PASSWORD=${DB_PASSWORD}
      - SPRING_FLYWAY_URL=${FLYWAY_URL}
      - SPRING_FLYWAY_USER=${DB_USERNAME}
      - SPRING_FLYWAY_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - streaming-network

  streaming-service:
    build: ./streaming-service
    container_name: sonus-streaming-service
    environment:
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESSKEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRETKEY=${MINIO_SECRET_KEY}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9094
    depends_on:
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy

    networks:
      - streaming-network

  upload-content-service:
    build: ./upload-content-service
    container_name: sonus-upload-content-service
    environment:
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESSKEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRETKEY=${MINIO_SECRET_KEY}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - SPRING_MONGODB_URI=${UPLOAD_DB_MONGO_URI}
    depends_on:
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - streaming-network

  artist-service:
    build: ./artist-service
    container_name: sonus-artist-service
    environment:
      - SPRING_DATA_MONGODB_URI=${ARTIST_DB_MONGO_URI}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - streaming-network

  catalog-service:
    build: ./catalog-service
    container_name: sonus-catalog-service
    environment:
      - SPRING_DATA_MONGODB_URI=${CATALOG_DB_MONGO_URI}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - streaming-network

  user-library-service:
    build: ./user-library-service
    container_name: sonus-user-library-service
    environment:
      - SPRING_DATA_MONGODB_URI=${USER_LIB_DB_MONGO_URI}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - streaming-network

volumes:
  kafka_data:
  postgres_data:
  mongo_data:
  minio_data:

networks:
  streaming-network:
    driver: bridge